name: Update Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: New changelog version
        type: string
        required: true
        default: ""
      distro:
        description: Changelog distro
        type: string
        required: true
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-24.04
    container: "ghcr.io/regolith-linux/ci-ubuntu:noble-amd64"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Changelog
        run: gbp dch --force-distribution --distribution "${{ inputs.distro }}" -N "${{ inputs.version }}" --debian-branch="${{ github.ref_name }}"

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_BROADCAST_TOKEN2 }}
        with:
          file_pattern: "debian/changelog"
          commit_message: "chore: bump changelog version to ${{ inputs.version }}"
          commit_user_name: regolith-ci-bot
          commit_user_email: bot@regolith-desktop.com
          commit_author: "regolith-ci-bot <bot@regolith-desktop.com>"
